###
POST http://localhost:3001/api/patients/d27736ec-f723-11e9-8f0b-362b9e155667/entries HTTP/1.1
Content-Type: application/json

{
    "description": "good",
    "specialist": "MD housesdfs",
    "date": "2023-02-02",
    "type": "HealthCheck",
    "healthCheckRating": 0,
    "diagnosisCodes": ["F43.2", "L20"]
}

###
GET http://localhost:3001/api/patients/d27736ec-f723-11e9-8f0b-362b9e155667/ HTTP/1.1
Content-Type: application/json

{
    "description": "good",
    "specialist": "MD housesdfs",
    "date": "2023-02-02",
    "type": "HealthCheck",
    "healthCheckRating": 0
}

###
POST http://localhost:3001/api/patients/ HTTP/1.1
Content-Type: application/json

{
    "name": "David Doe",
    "dateOfBirth": "2023-07-02",
    "ssn": "090874-154X",
    "gender": "male",
    "occupation": "Developper"
}